image:
  name: hashicorp/terraform:1.16
  entrypoint: [""]

stages:
  - validate
  - plan
  - apply

variables:
  TF_IN_AUTOMATION: "true"
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_VAR_yandex_cloud_token: ${YC_TOKEN}
  TF_VAR_yandex_cloud_id: ${YC_CLOUD_ID}
  TF_VAR_folder_id: ${YC_FOLDER_ID}

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .terraform/

before_script:
  - echo ${YC_SERVICE_ACCOUNT_KEY} > /tmp/sa-key.json
  - export TF_VAR_service_account_key_file="/tmp/sa-key.json"
  - terraform init -backend-config="access_key=${YC_ACCESS_KEY}" -backend-config="secret_key=${YC_SECRET_KEY}"

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=plan.tfplan
  artifacts:
    paths:
      - plan.tfplan
    expire_in: 1 hour

apply:
  stage: apply
  script:
    - terraform apply -auto-approve plan.tfplan
  dependencies:
    - plan
  when: manual
  only:
    - main
  before_script:
    - echo ${YC_SERVICE_ACCOUNT_KEY} > /tmp/sa-key.json